#!/usr/bin/perl 

$start = "2002-02-15";
$end = "2002-04-15";
open(F, "cvs log -N -d '$start<$end' 2>&1|") || die "cannot run cvs: $!";

while(<F>) {
if(/^=============================================================================$/) {
    $print = 0;
}

if(/^RCS file:/) {
    $rcs = $_;
    $print = 0;
}

if(/^----------------------------$/) {
   print "=============================================\n";
   print $rcs;
   $print = 1;
}

print if $print;
}

close(F);
