# $Id: Makefile,v 1.1 2004/05/01 04:15:23 greear Exp $

BUILD = ../../build

include $(BUILD)/Makefile.pre

DEFINES += USE_PTHREADS

PACKAGES += PTHREAD RTP UTIL QUICKNET

VERIFY_TESTCASES = \
	EndianVerify.cxx

include $(BUILD)/Makefile.post
