# $Id: Makefile,v 1.1 2004/05/01 04:15:25 greear Exp $
#

BUILD = ../../build

include $(BUILD)/Makefile.pre

PACKAGES += SDP UTIL PTHREAD

# names of programs (e.g. test programs) to be compiled
#

TESTPROGRAMS=\
	SdpTest.cxx

VERIFY_TESTCASES = \
	SdpAttributeTest.cxx\
	SdpSessionTest.cxx

include $(BUILD)/Makefile.post
