# $Id: Makefile,v 1.1 2004/05/01 04:15:25 greear Exp $

BUILD = ../../build

include $(BUILD)/Makefile.pre

PACKAGES += PTHREAD SIP SDP2 SIPMGCP UTIL LIBCEXT LIBXML OPENSSL

TESTPROGRAMS = \
	recvInvite.cxx \
	sendInvite.cxx \
        sendRegister.cxx \
        recvRegister.cxx \
	sendInvite2.cxx \
	sendInvite3.cxx \
	recvInvite2.cxx 

#	autoCall.cxx


include $(BUILD)/Makefile.post
