# $Id: Makefile,v 1.1 2004/05/01 04:15:22 greear Exp $
#

BUILD = ../../build

include $(BUILD)/Makefile.pre

PACKAGES += RADIUS UTIL PTHREAD LIBCEXT OPENSSL

TESTPROGRAMS = \
	radiusTest.cxx \
	radiusClient.cxx \
	radiusServer.cxx


SRC = \
	RadiusTestConfiguration.cxx

include $(BUILD)/Makefile.post
