/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_main_window (void)
{
  GtkWidget *main_window;
  GtkWidget *main_window_manager;
  GtkWidget *toolbox;
  GtkWidget *menubar;
  guint tmp_key;
  GtkWidget *file1;
  GtkWidget *file1_menu;
  GtkAccelGroup *file1_menu_accels;
  GtkWidget *exit;
  GtkWidget *settings1;
  GtkWidget *settings1_menu;
  GtkAccelGroup *settings1_menu_accels;
  GtkWidget *basic_configuration1;
  GtkWidget *advanced1;
  GtkWidget *view1;
  GtkWidget *view1_menu;
  GtkAccelGroup *view1_menu_accels;
  GtkWidget *messages1;
  GtkWidget *tools1;
  GtkWidget *tools1_menu;
  GtkAccelGroup *tools1_menu_accels;
  GtkWidget *clear_history1;
  GtkWidget *fixed1;
  GtkWidget *talk_button;
  GtkWidget *dial_combo;
  GtkWidget *dial_entry;
  GtkWidget *hbox5;
  GtkWidget *username_eventbox;
  GtkWidget *name_label;
  GtkWidget *blank_label1;
  GtkWidget *registerbox;
  GtkWidget *blank_label2;
  GtkWidget *register_eventbox;
  GtkWidget *msgbox;
  GtkWidget *message_entry;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  main_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (main_window), "main_window", main_window);
  gtk_widget_set_usize (main_window, 280, 170);
  gtk_window_set_title (GTK_WINDOW (main_window), _("SIPSet by VOVIDA.ORG"));
  gtk_window_set_position (GTK_WINDOW (main_window), GTK_WIN_POS_CENTER);

  main_window_manager = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (main_window_manager);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "main_window_manager", main_window_manager,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (main_window_manager);
  gtk_container_add (GTK_CONTAINER (main_window), main_window_manager);

  toolbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (toolbox);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "toolbox", toolbox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbox);
  gtk_box_pack_start (GTK_BOX (main_window_manager), toolbox, FALSE, FALSE, 0);

  menubar = gtk_menu_bar_new ();
  gtk_widget_ref (menubar);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "menubar", menubar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar);
  gtk_box_pack_start (GTK_BOX (toolbox), menubar, FALSE, FALSE, 0);
  gtk_widget_set_usize (menubar, 0, 0);

  file1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (file1)->child),
                                   _("_File"));
  gtk_widget_add_accelerator (file1, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_ref (file1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "file1", file1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file1);
  gtk_container_add (GTK_CONTAINER (menubar), file1);

  file1_menu = gtk_menu_new ();
  gtk_widget_ref (file1_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "file1_menu", file1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file1), file1_menu);
  file1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (file1_menu));

  exit = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (exit)->child),
                                   _("E_xit"));
  gtk_widget_add_accelerator (exit, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (exit);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "exit", exit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exit);
  gtk_container_add (GTK_CONTAINER (file1_menu), exit);
  gtk_tooltips_set_tip (tooltips, exit, _("Exit from program"), NULL);
  gtk_widget_add_accelerator (exit, "activate", accel_group,
                              GDK_Q, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  settings1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (settings1)->child),
                                   _("_Settings"));
  gtk_widget_add_accelerator (settings1, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_ref (settings1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "settings1", settings1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (settings1);
  gtk_container_add (GTK_CONTAINER (menubar), settings1);

  settings1_menu = gtk_menu_new ();
  gtk_widget_ref (settings1_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "settings1_menu", settings1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (settings1), settings1_menu);
  settings1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (settings1_menu));

  basic_configuration1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (basic_configuration1)->child),
                                   _("_Basic Configuration"));
  gtk_widget_add_accelerator (basic_configuration1, "activate_item", settings1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (basic_configuration1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "basic_configuration1", basic_configuration1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (basic_configuration1);
  gtk_container_add (GTK_CONTAINER (settings1_menu), basic_configuration1);

  advanced1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (advanced1)->child),
                                   _("_Advanced Configuration"));
  gtk_widget_add_accelerator (advanced1, "activate_item", settings1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (advanced1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "advanced1", advanced1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (advanced1);
  gtk_container_add (GTK_CONTAINER (settings1_menu), advanced1);

  view1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (view1)->child),
                                   _("_View"));
  gtk_widget_add_accelerator (view1, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_ref (view1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "view1", view1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (view1);
  gtk_container_add (GTK_CONTAINER (menubar), view1);

  view1_menu = gtk_menu_new ();
  gtk_widget_ref (view1_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "view1_menu", view1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (view1), view1_menu);
  view1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (view1_menu));

  messages1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (messages1)->child),
                                   _("_Log Messages"));
  gtk_widget_add_accelerator (messages1, "activate_item", view1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (messages1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "messages1", messages1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (messages1);
  gtk_container_add (GTK_CONTAINER (view1_menu), messages1);

  tools1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (tools1)->child),
                                   _("_Tools"));
  gtk_widget_add_accelerator (tools1, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_ref (tools1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "tools1", tools1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tools1);
  gtk_container_add (GTK_CONTAINER (menubar), tools1);

  tools1_menu = gtk_menu_new ();
  gtk_widget_ref (tools1_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "tools1_menu", tools1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (tools1), tools1_menu);
  tools1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (tools1_menu));

  clear_history1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (clear_history1)->child),
                                   _("_Clear History"));
  gtk_widget_add_accelerator (clear_history1, "activate_item", tools1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (clear_history1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "clear_history1", clear_history1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clear_history1);
  gtk_container_add (GTK_CONTAINER (tools1_menu), clear_history1);

  fixed1 = gtk_fixed_new ();
  gtk_widget_ref (fixed1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "fixed1", fixed1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (fixed1);
  gtk_box_pack_start (GTK_BOX (main_window_manager), fixed1, TRUE, TRUE, 0);
  gtk_widget_set_usize (fixed1, 300, 100);

  talk_button = gtk_button_new_with_label (_("Talk"));
  gtk_widget_ref (talk_button);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "talk_button", talk_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (talk_button);
  gtk_fixed_put (GTK_FIXED (fixed1), talk_button, 40, 72);
  gtk_widget_set_uposition (talk_button, 40, 72);
  gtk_widget_set_usize (talk_button, 61, 22);
  gtk_tooltips_set_tip (tooltips, talk_button, _("Make a call"), NULL);

  dial_combo = gtk_combo_new ();
  gtk_widget_ref (dial_combo);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "dial_combo", dial_combo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (dial_combo);
  gtk_fixed_put (GTK_FIXED (fixed1), dial_combo, 40, 40);
  gtk_widget_set_uposition (dial_combo, 40, 40);
  gtk_widget_set_usize (dial_combo, 197, 22);
  GTK_WIDGET_SET_FLAGS (dial_combo, GTK_CAN_DEFAULT);

  dial_entry = GTK_COMBO (dial_combo)->entry;
  gtk_widget_ref (dial_entry);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "dial_entry", dial_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (dial_entry);
  gtk_tooltips_set_tip (tooltips, dial_entry, _("Enter SIP URI or Phone Number"), NULL);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox5);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "hbox5", hbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox5);
  gtk_fixed_put (GTK_FIXED (fixed1), hbox5, 40, 16);
  gtk_widget_set_uposition (hbox5, 40, 16);
  gtk_widget_set_usize (hbox5, 232, 16);

  username_eventbox = gtk_event_box_new ();
  gtk_widget_ref (username_eventbox);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "username_eventbox", username_eventbox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (username_eventbox);
  gtk_box_pack_start (GTK_BOX (hbox5), username_eventbox, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, username_eventbox, _("Your display name"), NULL);

  name_label = gtk_label_new (_("name"));
  gtk_widget_ref (name_label);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "name_label", name_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (name_label);
  gtk_container_add (GTK_CONTAINER (username_eventbox), name_label);
  gtk_label_set_justify (GTK_LABEL (name_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (name_label), 0, 0.5);

  blank_label1 = gtk_label_new ("");
  gtk_widget_ref (blank_label1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "blank_label1", blank_label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (blank_label1);
  gtk_box_pack_start (GTK_BOX (hbox5), blank_label1, TRUE, TRUE, 0);

  registerbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (registerbox);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "registerbox", registerbox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (registerbox);
  gtk_box_pack_start (GTK_BOX (main_window_manager), registerbox, TRUE, TRUE, 0);

  blank_label2 = gtk_label_new ("");
  gtk_widget_ref (blank_label2);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "blank_label2", blank_label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (blank_label2);
  gtk_box_pack_start (GTK_BOX (registerbox), blank_label2, TRUE, TRUE, 0);

  register_eventbox = gtk_event_box_new ();
  gtk_widget_ref (register_eventbox);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "register_eventbox", register_eventbox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (register_eventbox);
  gtk_box_pack_start (GTK_BOX (registerbox), register_eventbox, FALSE, FALSE, 3);
  gtk_widget_set_usize (register_eventbox, 16, 16);
  gtk_tooltips_set_tip (tooltips, register_eventbox, _("unregistered"), NULL);

  msgbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (msgbox);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "msgbox", msgbox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (msgbox);
  gtk_box_pack_start (GTK_BOX (main_window_manager), msgbox, FALSE, FALSE, 0);

  message_entry = gtk_entry_new ();
  gtk_widget_ref (message_entry);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "message_entry", message_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (message_entry);
  gtk_box_pack_start (GTK_BOX (msgbox), message_entry, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (message_entry, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, message_entry, _("Status message"), NULL);
  gtk_entry_set_editable (GTK_ENTRY (message_entry), FALSE);

  gtk_signal_connect (GTK_OBJECT (main_window), "destroy",
                      GTK_SIGNAL_FUNC (on_main_window_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (exit), "activate",
                      GTK_SIGNAL_FUNC (on_exit_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (basic_configuration1), "activate",
                      GTK_SIGNAL_FUNC (on_basic_configuration1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (advanced1), "activate",
                      GTK_SIGNAL_FUNC (on_advanced1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (messages1), "activate",
                      GTK_SIGNAL_FUNC (on_messages1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clear_history1), "activate",
                      GTK_SIGNAL_FUNC (on_clear_history1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (talk_button), "clicked",
                      GTK_SIGNAL_FUNC (on_talk_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (dial_entry), "activate",
                      GTK_SIGNAL_FUNC (on_dial_entry_activate),
                      NULL);

  gtk_widget_grab_default (dial_combo);
  gtk_object_set_data (GTK_OBJECT (main_window), "tooltips", tooltips);

  gtk_window_add_accel_group (GTK_WINDOW (main_window), accel_group);

  return main_window;
}

GtkWidget*
create_basic_config_dialog (void)
{
  GtkWidget *basic_config_dialog;
  GtkWidget *dialog_vbox1;
  GtkWidget *basic_config_table;
  GtkWidget *User_Name;
  GtkWidget *Pass_Word;
  GtkWidget *repeat_password;
  GtkWidget *Proxy_Server;
  GtkWidget *frame1;
  GtkWidget *user_name_label;
  GtkWidget *frame2;
  GtkWidget *proxy_address_label;
  GtkWidget *frame3;
  GtkWidget *password_label;
  GtkWidget *frame4;
  GtkWidget *repeat_password_label;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbuttonbox1;
  GtkWidget *basic_config_ok;
  GtkWidget *basic_config_cancel;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  basic_config_dialog = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (basic_config_dialog), "basic_config_dialog", basic_config_dialog);
  gtk_widget_set_usize (basic_config_dialog, 300, 160);
  gtk_window_set_title (GTK_WINDOW (basic_config_dialog), _("Basic Configuration"));
  gtk_window_set_position (GTK_WINDOW (basic_config_dialog), GTK_WIN_POS_CENTER);
  gtk_window_set_policy (GTK_WINDOW (basic_config_dialog), TRUE, TRUE, FALSE);
  gtk_window_set_wmclass (GTK_WINDOW (basic_config_dialog), "basic_config_dialog", "");

  dialog_vbox1 = GTK_DIALOG (basic_config_dialog)->vbox;
  gtk_object_set_data (GTK_OBJECT (basic_config_dialog), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);
  gtk_widget_set_usize (dialog_vbox1, 274, 149);

  basic_config_table = gtk_table_new (4, 2, FALSE);
  gtk_widget_ref (basic_config_table);
  gtk_object_set_data_full (GTK_OBJECT (basic_config_dialog), "basic_config_table", basic_config_table,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (basic_config_table);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), basic_config_table, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (basic_config_table), 5);
  gtk_table_set_row_spacings (GTK_TABLE (basic_config_table), 2);
  gtk_table_set_col_spacings (GTK_TABLE (basic_config_table), 5);

  User_Name = gtk_entry_new ();
  gtk_widget_ref (User_Name);
  gtk_object_set_data_full (GTK_OBJECT (basic_config_dialog), "User_Name", User_Name,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (User_Name);
  gtk_table_attach (GTK_TABLE (basic_config_table), User_Name, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  Pass_Word = gtk_entry_new ();
  gtk_widget_ref (Pass_Word);
  gtk_object_set_data_full (GTK_OBJECT (basic_config_dialog), "Pass_Word", Pass_Word,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Pass_Word);
  gtk_table_attach (GTK_TABLE (basic_config_table), Pass_Word, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_visibility (GTK_ENTRY (Pass_Word), FALSE);

  repeat_password = gtk_entry_new ();
  gtk_widget_ref (repeat_password);
  gtk_object_set_data_full (GTK_OBJECT (basic_config_dialog), "repeat_password", repeat_password,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (repeat_password);
  gtk_table_attach (GTK_TABLE (basic_config_table), repeat_password, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, repeat_password, _("Repeat password"), NULL);
  gtk_entry_set_visibility (GTK_ENTRY (repeat_password), FALSE);

  Proxy_Server = gtk_entry_new ();
  gtk_widget_ref (Proxy_Server);
  gtk_object_set_data_full (GTK_OBJECT (basic_config_dialog), "Proxy_Server", Proxy_Server,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Proxy_Server);
  gtk_table_attach (GTK_TABLE (basic_config_table), Proxy_Server, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_ref (frame1);
  gtk_object_set_data_full (GTK_OBJECT (basic_config_dialog), "frame1", frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame1);
  gtk_table_attach (GTK_TABLE (basic_config_table), frame1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame1), GTK_SHADOW_NONE);

  user_name_label = gtk_label_new (_("User Name"));
  gtk_widget_ref (user_name_label);
  gtk_object_set_data_full (GTK_OBJECT (basic_config_dialog), "user_name_label", user_name_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (user_name_label);
  gtk_container_add (GTK_CONTAINER (frame1), user_name_label);
  gtk_misc_set_alignment (GTK_MISC (user_name_label), 1, 0.5);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_ref (frame2);
  gtk_object_set_data_full (GTK_OBJECT (basic_config_dialog), "frame2", frame2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame2);
  gtk_table_attach (GTK_TABLE (basic_config_table), frame2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame2), GTK_SHADOW_NONE);

  proxy_address_label = gtk_label_new (_("SIP Proxy Server"));
  gtk_widget_ref (proxy_address_label);
  gtk_object_set_data_full (GTK_OBJECT (basic_config_dialog), "proxy_address_label", proxy_address_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (proxy_address_label);
  gtk_container_add (GTK_CONTAINER (frame2), proxy_address_label);
  gtk_label_set_justify (GTK_LABEL (proxy_address_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (proxy_address_label), 1, 0.5);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_ref (frame3);
  gtk_object_set_data_full (GTK_OBJECT (basic_config_dialog), "frame3", frame3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame3);
  gtk_table_attach (GTK_TABLE (basic_config_table), frame3, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame3), GTK_SHADOW_NONE);

  password_label = gtk_label_new (_("Password"));
  gtk_widget_ref (password_label);
  gtk_object_set_data_full (GTK_OBJECT (basic_config_dialog), "password_label", password_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (password_label);
  gtk_container_add (GTK_CONTAINER (frame3), password_label);
  gtk_label_set_justify (GTK_LABEL (password_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (password_label), 1, 0.5);

  frame4 = gtk_frame_new (NULL);
  gtk_widget_ref (frame4);
  gtk_object_set_data_full (GTK_OBJECT (basic_config_dialog), "frame4", frame4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame4);
  gtk_table_attach (GTK_TABLE (basic_config_table), frame4, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame4), GTK_SHADOW_NONE);

  repeat_password_label = gtk_label_new (_("Repeat Password"));
  gtk_widget_ref (repeat_password_label);
  gtk_object_set_data_full (GTK_OBJECT (basic_config_dialog), "repeat_password_label", repeat_password_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (repeat_password_label);
  gtk_container_add (GTK_CONTAINER (frame4), repeat_password_label);
  gtk_misc_set_alignment (GTK_MISC (repeat_password_label), 1, 0.5);

  dialog_action_area1 = GTK_DIALOG (basic_config_dialog)->action_area;
  gtk_object_set_data (GTK_OBJECT (basic_config_dialog), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area1), 10);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (basic_config_dialog), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (dialog_action_area1), hbuttonbox1, FALSE, FALSE, 0);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox1), 5);

  basic_config_ok = gtk_button_new_with_label (_("OK"));
  gtk_widget_ref (basic_config_ok);
  gtk_object_set_data_full (GTK_OBJECT (basic_config_dialog), "basic_config_ok", basic_config_ok,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (basic_config_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), basic_config_ok);
  GTK_WIDGET_SET_FLAGS (basic_config_ok, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, basic_config_ok, _("save changes"), NULL);

  basic_config_cancel = gtk_button_new_with_label (_("Cancel"));
  gtk_widget_ref (basic_config_cancel);
  gtk_object_set_data_full (GTK_OBJECT (basic_config_dialog), "basic_config_cancel", basic_config_cancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (basic_config_cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), basic_config_cancel);
  GTK_WIDGET_SET_FLAGS (basic_config_cancel, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, basic_config_cancel, _("exit without saving"), NULL);

  gtk_signal_connect (GTK_OBJECT (basic_config_ok), "clicked",
                      GTK_SIGNAL_FUNC (on_basic_config_ok_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (basic_config_cancel), "clicked",
                      GTK_SIGNAL_FUNC (on_basic_config_cancel_clicked),
                      NULL);

  gtk_widget_grab_focus (User_Name);
  gtk_widget_grab_default (basic_config_ok);
  gtk_object_set_data (GTK_OBJECT (basic_config_dialog), "tooltips", tooltips);

  return basic_config_dialog;
}

GtkWidget*
create_advanced_config_dialog (void)
{
  GtkWidget *advanced_config_dialog;
  GtkWidget *dialog_vbox2;
  GtkWidget *scrolledwindow2;
  GtkWidget *viewport1;
  GtkWidget *advanced_config_table;
  GtkWidget *Register_To;
  GtkWidget *Register_Expires;
  GtkWidget *Display_Name;
  GtkWidget *sip_transport_combo;
  GList *sip_transport_combo_items = NULL;
  GtkWidget *SIP_Transport;
  GtkWidget *Register_From;
  GtkWidget *Min_RTP_Port;
  GtkWidget *Max_RTP_Port;
  GtkWidget *LogFilename;
  GtkWidget *log_level_combo;
  GList *log_level_combo_items = NULL;
  GtkWidget *LogLevel;
  GtkWidget *hseparator1;
  GtkWidget *hbox1;
  GtkWidget *label1;
  GtkWidget *hseparator2;
  GtkWidget *Device_Name;
  GtkWidget *hseparator3;
  GtkWidget *hbox2;
  GtkWidget *label2;
  GtkWidget *hseparator4;
  GtkWidget *hseparator5;
  GtkWidget *hbox3;
  GtkWidget *label3;
  GtkWidget *hseparator6;
  GtkWidget *hbox4;
  GtkWidget *label4;
  GtkWidget *hseparator8;
  GtkWidget *frame5;
  GtkWidget *display_name_label;
  GtkWidget *frame7;
  GtkWidget *sip_transport_label;
  GtkWidget *frame8;
  GtkWidget *register_from_label;
  GtkWidget *frame9;
  GtkWidget *register_to_label;
  GtkWidget *frame10;
  GtkWidget *register_expires_label;
  GtkWidget *frame11;
  GtkWidget *device_name_label;
  GtkWidget *frame12;
  GtkWidget *min_rtp_port_label;
  GtkWidget *frame13;
  GtkWidget *max_rtp_port_label;
  GtkWidget *frame14;
  GtkWidget *log_filename_label;
  GtkWidget *frame15;
  GtkWidget *log_level_label;
  GtkWidget *NATAddress_IP;
  GtkWidget *frame17;
  GtkWidget *nat_ip_label;
  GtkWidget *Video;
  GtkWidget *hseparator9;
  GtkWidget *Wave_File_L;
  GtkWidget *Wave_File;
  GtkWidget *LANforge;
  GtkWidget *dialog_action_area2;
  GtkWidget *hbuttonbox2;
  GtkWidget *advanced_config_ok;
  GtkWidget *advanced_config_cancel;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  advanced_config_dialog = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (advanced_config_dialog), "advanced_config_dialog", advanced_config_dialog);
  gtk_widget_set_usize (advanced_config_dialog, 300, 550);
  gtk_window_set_title (GTK_WINDOW (advanced_config_dialog), _("Advanced Configuration"));
  gtk_window_set_position (GTK_WINDOW (advanced_config_dialog), GTK_WIN_POS_CENTER);
  gtk_window_set_policy (GTK_WINDOW (advanced_config_dialog), TRUE, TRUE, FALSE);

  dialog_vbox2 = GTK_DIALOG (advanced_config_dialog)->vbox;
  gtk_object_set_data (GTK_OBJECT (advanced_config_dialog), "dialog_vbox2", dialog_vbox2);
  gtk_widget_show (dialog_vbox2);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), scrolledwindow2, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_ref (viewport1);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "viewport1", viewport1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), viewport1);

  advanced_config_table = gtk_table_new (18, 2, FALSE);
  gtk_widget_ref (advanced_config_table);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "advanced_config_table", advanced_config_table,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (advanced_config_table);
  gtk_container_add (GTK_CONTAINER (viewport1), advanced_config_table);
  gtk_container_set_border_width (GTK_CONTAINER (advanced_config_table), 5);
  gtk_table_set_row_spacings (GTK_TABLE (advanced_config_table), 2);
  gtk_table_set_col_spacings (GTK_TABLE (advanced_config_table), 5);

  Register_To = gtk_entry_new ();
  gtk_widget_ref (Register_To);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "Register_To", Register_To,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Register_To);
  gtk_table_attach (GTK_TABLE (advanced_config_table), Register_To, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  Register_Expires = gtk_entry_new ();
  gtk_widget_ref (Register_Expires);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "Register_Expires", Register_Expires,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Register_Expires);
  gtk_table_attach (GTK_TABLE (advanced_config_table), Register_Expires, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  Display_Name = gtk_entry_new ();
  gtk_widget_ref (Display_Name);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "Display_Name", Display_Name,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Display_Name);
  gtk_table_attach (GTK_TABLE (advanced_config_table), Display_Name, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  sip_transport_combo = gtk_combo_new ();
  gtk_widget_ref (sip_transport_combo);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "sip_transport_combo", sip_transport_combo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (sip_transport_combo);
  gtk_table_attach (GTK_TABLE (advanced_config_table), sip_transport_combo, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (sip_transport_combo), TRUE, FALSE);
  sip_transport_combo_items = g_list_append (sip_transport_combo_items, (gpointer) _("UDP"));
  sip_transport_combo_items = g_list_append (sip_transport_combo_items, (gpointer) _("TCP"));
  gtk_combo_set_popdown_strings (GTK_COMBO (sip_transport_combo), sip_transport_combo_items);
  g_list_free (sip_transport_combo_items);

  SIP_Transport = GTK_COMBO (sip_transport_combo)->entry;
  gtk_widget_ref (SIP_Transport);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "SIP_Transport", SIP_Transport,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (SIP_Transport);
  gtk_entry_set_text (GTK_ENTRY (SIP_Transport), _("UDP"));

  Register_From = gtk_entry_new ();
  gtk_widget_ref (Register_From);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "Register_From", Register_From,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Register_From);
  gtk_table_attach (GTK_TABLE (advanced_config_table), Register_From, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  Min_RTP_Port = gtk_entry_new ();
  gtk_widget_ref (Min_RTP_Port);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "Min_RTP_Port", Min_RTP_Port,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Min_RTP_Port);
  gtk_table_attach (GTK_TABLE (advanced_config_table), Min_RTP_Port, 1, 2, 9, 10,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  Max_RTP_Port = gtk_entry_new ();
  gtk_widget_ref (Max_RTP_Port);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "Max_RTP_Port", Max_RTP_Port,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Max_RTP_Port);
  gtk_table_attach (GTK_TABLE (advanced_config_table), Max_RTP_Port, 1, 2, 10, 11,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  LogFilename = gtk_entry_new ();
  gtk_widget_ref (LogFilename);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "LogFilename", LogFilename,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (LogFilename);
  gtk_table_attach (GTK_TABLE (advanced_config_table), LogFilename, 1, 2, 15, 16,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, LogFilename, _("File for UA debug messages"), NULL);

  log_level_combo = gtk_combo_new ();
  gtk_widget_ref (log_level_combo);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "log_level_combo", log_level_combo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (log_level_combo);
  gtk_table_attach (GTK_TABLE (advanced_config_table), log_level_combo, 1, 2, 16, 17,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (log_level_combo), TRUE, FALSE);
  gtk_combo_set_use_arrows_always (GTK_COMBO (log_level_combo), TRUE);
  log_level_combo_items = g_list_append (log_level_combo_items, (gpointer) _("LOG_EMERG"));
  log_level_combo_items = g_list_append (log_level_combo_items, (gpointer) _("LOG_ALERT"));
  log_level_combo_items = g_list_append (log_level_combo_items, (gpointer) _("LOG_CRIT"));
  log_level_combo_items = g_list_append (log_level_combo_items, (gpointer) _("LOG_ERR"));
  log_level_combo_items = g_list_append (log_level_combo_items, (gpointer) _("LOG_WARNING"));
  log_level_combo_items = g_list_append (log_level_combo_items, (gpointer) _("LOG_NOTICE"));
  log_level_combo_items = g_list_append (log_level_combo_items, (gpointer) _("LOG_INFO"));
  log_level_combo_items = g_list_append (log_level_combo_items, (gpointer) _("LOG_DEBUG"));
  log_level_combo_items = g_list_append (log_level_combo_items, (gpointer) _("LOG_DEBUG_STACK"));
  gtk_combo_set_popdown_strings (GTK_COMBO (log_level_combo), log_level_combo_items);
  g_list_free (log_level_combo_items);

  LogLevel = GTK_COMBO (log_level_combo)->entry;
  gtk_widget_ref (LogLevel);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "LogLevel", LogLevel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (LogLevel);
  gtk_tooltips_set_tip (tooltips, LogLevel, _("Verbosity of log messages"), NULL);
  gtk_entry_set_text (GTK_ENTRY (LogLevel), _("LOG_ERR"));

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator1);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "hseparator1", hseparator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator1);
  gtk_table_attach (GTK_TABLE (advanced_config_table), hseparator1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_table_attach (GTK_TABLE (advanced_config_table), hbox1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label1 = gtk_label_new (_("General"));
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator2);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "hseparator2", hseparator2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (hbox1), hseparator2, TRUE, TRUE, 0);

  Device_Name = gtk_entry_new ();
  gtk_widget_ref (Device_Name);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "Device_Name", Device_Name,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Device_Name);
  gtk_table_attach (GTK_TABLE (advanced_config_table), Device_Name, 1, 2, 8, 9,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator3);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "hseparator3", hseparator3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator3);
  gtk_table_attach (GTK_TABLE (advanced_config_table), hseparator3, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_table_attach (GTK_TABLE (advanced_config_table), hbox2, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label2 = gtk_label_new (_("User Registration"));
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label2), 0, 5);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator4);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "hseparator4", hseparator4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator4);
  gtk_box_pack_start (GTK_BOX (hbox2), hseparator4, TRUE, TRUE, 0);

  hseparator5 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator5);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "hseparator5", hseparator5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator5);
  gtk_table_attach (GTK_TABLE (advanced_config_table), hseparator5, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_table_attach (GTK_TABLE (advanced_config_table), hbox3, 1, 2, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label3 = gtk_label_new (_("Media"));
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label3), 0, 5);

  hseparator6 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator6);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "hseparator6", hseparator6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator6);
  gtk_box_pack_start (GTK_BOX (hbox3), hseparator6, TRUE, TRUE, 0);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_table_attach (GTK_TABLE (advanced_config_table), hbox4, 1, 2, 14, 15,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label4 = gtk_label_new (_("Log"));
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label4), 0, 5);

  hseparator8 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator8);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "hseparator8", hseparator8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator8);
  gtk_box_pack_start (GTK_BOX (hbox4), hseparator8, TRUE, TRUE, 0);

  frame5 = gtk_frame_new (NULL);
  gtk_widget_ref (frame5);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "frame5", frame5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame5);
  gtk_table_attach (GTK_TABLE (advanced_config_table), frame5, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame5), GTK_SHADOW_NONE);

  display_name_label = gtk_label_new (_("Display Name"));
  gtk_widget_ref (display_name_label);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "display_name_label", display_name_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (display_name_label);
  gtk_container_add (GTK_CONTAINER (frame5), display_name_label);
  gtk_misc_set_alignment (GTK_MISC (display_name_label), 1, 0.5);

  frame7 = gtk_frame_new (NULL);
  gtk_widget_ref (frame7);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "frame7", frame7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame7);
  gtk_table_attach (GTK_TABLE (advanced_config_table), frame7, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame7), GTK_SHADOW_NONE);

  sip_transport_label = gtk_label_new (_("SIP Transport"));
  gtk_widget_ref (sip_transport_label);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "sip_transport_label", sip_transport_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (sip_transport_label);
  gtk_container_add (GTK_CONTAINER (frame7), sip_transport_label);
  gtk_misc_set_alignment (GTK_MISC (sip_transport_label), 1, 0.5);

  frame8 = gtk_frame_new (NULL);
  gtk_widget_ref (frame8);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "frame8", frame8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame8);
  gtk_table_attach (GTK_TABLE (advanced_config_table), frame8, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame8), GTK_SHADOW_NONE);

  register_from_label = gtk_label_new (_("Register From"));
  gtk_widget_ref (register_from_label);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "register_from_label", register_from_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (register_from_label);
  gtk_container_add (GTK_CONTAINER (frame8), register_from_label);
  gtk_misc_set_alignment (GTK_MISC (register_from_label), 1, 0.5);

  frame9 = gtk_frame_new (NULL);
  gtk_widget_ref (frame9);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "frame9", frame9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame9);
  gtk_table_attach (GTK_TABLE (advanced_config_table), frame9, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame9), GTK_SHADOW_NONE);

  register_to_label = gtk_label_new (_("Registrar"));
  gtk_widget_ref (register_to_label);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "register_to_label", register_to_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (register_to_label);
  gtk_container_add (GTK_CONTAINER (frame9), register_to_label);
  gtk_misc_set_alignment (GTK_MISC (register_to_label), 1, 0.5);

  frame10 = gtk_frame_new (NULL);
  gtk_widget_ref (frame10);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "frame10", frame10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame10);
  gtk_table_attach (GTK_TABLE (advanced_config_table), frame10, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame10), GTK_SHADOW_NONE);

  register_expires_label = gtk_label_new (_("Expires"));
  gtk_widget_ref (register_expires_label);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "register_expires_label", register_expires_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (register_expires_label);
  gtk_container_add (GTK_CONTAINER (frame10), register_expires_label);
  gtk_misc_set_alignment (GTK_MISC (register_expires_label), 1, 0.5);

  frame11 = gtk_frame_new (NULL);
  gtk_widget_ref (frame11);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "frame11", frame11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame11);
  gtk_table_attach (GTK_TABLE (advanced_config_table), frame11, 0, 1, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame11), GTK_SHADOW_NONE);

  device_name_label = gtk_label_new (_("Sound Device"));
  gtk_widget_ref (device_name_label);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "device_name_label", device_name_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (device_name_label);
  gtk_container_add (GTK_CONTAINER (frame11), device_name_label);
  gtk_label_set_justify (GTK_LABEL (device_name_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (device_name_label), 1, 0.5);

  frame12 = gtk_frame_new (NULL);
  gtk_widget_ref (frame12);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "frame12", frame12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame12);
  gtk_table_attach (GTK_TABLE (advanced_config_table), frame12, 0, 1, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame12), GTK_SHADOW_NONE);

  min_rtp_port_label = gtk_label_new (_("Min RTP Port"));
  gtk_widget_ref (min_rtp_port_label);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "min_rtp_port_label", min_rtp_port_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (min_rtp_port_label);
  gtk_container_add (GTK_CONTAINER (frame12), min_rtp_port_label);
  gtk_misc_set_alignment (GTK_MISC (min_rtp_port_label), 1, 0.5);

  frame13 = gtk_frame_new (NULL);
  gtk_widget_ref (frame13);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "frame13", frame13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame13);
  gtk_table_attach (GTK_TABLE (advanced_config_table), frame13, 0, 1, 10, 11,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame13), GTK_SHADOW_NONE);

  max_rtp_port_label = gtk_label_new (_("Max RTP Port"));
  gtk_widget_ref (max_rtp_port_label);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "max_rtp_port_label", max_rtp_port_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (max_rtp_port_label);
  gtk_container_add (GTK_CONTAINER (frame13), max_rtp_port_label);
  gtk_misc_set_alignment (GTK_MISC (max_rtp_port_label), 1, 0.5);

  frame14 = gtk_frame_new (NULL);
  gtk_widget_ref (frame14);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "frame14", frame14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame14);
  gtk_table_attach (GTK_TABLE (advanced_config_table), frame14, 0, 1, 15, 16,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame14), GTK_SHADOW_NONE);

  log_filename_label = gtk_label_new (_("Log Filename"));
  gtk_widget_ref (log_filename_label);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "log_filename_label", log_filename_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (log_filename_label);
  gtk_container_add (GTK_CONTAINER (frame14), log_filename_label);
  gtk_misc_set_alignment (GTK_MISC (log_filename_label), 1, 0.5);

  frame15 = gtk_frame_new (NULL);
  gtk_widget_ref (frame15);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "frame15", frame15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame15);
  gtk_table_attach (GTK_TABLE (advanced_config_table), frame15, 0, 1, 16, 17,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame15), GTK_SHADOW_NONE);

  log_level_label = gtk_label_new (_("Log Level"));
  gtk_widget_ref (log_level_label);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "log_level_label", log_level_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (log_level_label);
  gtk_container_add (GTK_CONTAINER (frame15), log_level_label);
  gtk_misc_set_alignment (GTK_MISC (log_level_label), 1, 0.5);

  NATAddress_IP = gtk_entry_new ();
  gtk_widget_ref (NATAddress_IP);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "NATAddress_IP", NATAddress_IP,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (NATAddress_IP);
  gtk_table_attach (GTK_TABLE (advanced_config_table), NATAddress_IP, 1, 2, 11, 12,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  frame17 = gtk_frame_new (NULL);
  gtk_widget_ref (frame17);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "frame17", frame17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame17);
  gtk_table_attach (GTK_TABLE (advanced_config_table), frame17, 0, 1, 11, 12,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame17), GTK_SHADOW_NONE);

  nat_ip_label = gtk_label_new (_("NAT IP"));
  gtk_widget_ref (nat_ip_label);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "nat_ip_label", nat_ip_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (nat_ip_label);
  gtk_container_add (GTK_CONTAINER (frame17), nat_ip_label);
  gtk_misc_set_alignment (GTK_MISC (nat_ip_label), 1, 0.5);

  Video = gtk_check_button_new_with_label (_("Video"));
  gtk_widget_ref (Video);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "Video", Video,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Video);
  gtk_table_attach (GTK_TABLE (advanced_config_table), Video, 0, 1, 17, 18,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hseparator9 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator9);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "hseparator9", hseparator9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator9);
  gtk_table_attach (GTK_TABLE (advanced_config_table), hseparator9, 0, 1, 14, 15,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  Wave_File_L = gtk_label_new (_("Wave File"));
  gtk_widget_ref (Wave_File_L);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "Wave_File_L", Wave_File_L,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Wave_File_L);
  gtk_table_attach (GTK_TABLE (advanced_config_table), Wave_File_L, 0, 1, 12, 13,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (Wave_File_L), 1, 0.5);

  Wave_File = gtk_entry_new ();
  gtk_widget_ref (Wave_File);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "Wave_File", Wave_File,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Wave_File);
  gtk_table_attach (GTK_TABLE (advanced_config_table), Wave_File, 1, 2, 12, 13,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  LANforge = gtk_check_button_new_with_label (_("LANforge"));
  gtk_widget_ref (LANforge);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "LANforge", LANforge,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (LANforge);
  gtk_table_attach (GTK_TABLE (advanced_config_table), LANforge, 0, 1, 13, 14,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  dialog_action_area2 = GTK_DIALOG (advanced_config_dialog)->action_area;
  gtk_object_set_data (GTK_OBJECT (advanced_config_dialog), "dialog_action_area2", dialog_action_area2);
  gtk_widget_show (dialog_action_area2);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area2), 10);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox2);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "hbuttonbox2", hbuttonbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (dialog_action_area2), hbuttonbox2, FALSE, FALSE, 0);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox2), 5);

  advanced_config_ok = gtk_button_new_with_label (_("OK"));
  gtk_widget_ref (advanced_config_ok);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "advanced_config_ok", advanced_config_ok,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (advanced_config_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), advanced_config_ok);
  GTK_WIDGET_SET_FLAGS (advanced_config_ok, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, advanced_config_ok, _("save changes"), NULL);

  advanced_config_cancel = gtk_button_new_with_label (_("Cancel"));
  gtk_widget_ref (advanced_config_cancel);
  gtk_object_set_data_full (GTK_OBJECT (advanced_config_dialog), "advanced_config_cancel", advanced_config_cancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (advanced_config_cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), advanced_config_cancel);
  GTK_WIDGET_SET_FLAGS (advanced_config_cancel, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, advanced_config_cancel, _("exit without saving"), NULL);

  gtk_signal_connect_after (GTK_OBJECT (Display_Name), "key_press_event",
                            GTK_SIGNAL_FUNC (on_Display_Name_key_press_event),
                            NULL);
  gtk_signal_connect (GTK_OBJECT (Video), "toggled",
                      GTK_SIGNAL_FUNC (on_video_enabled_button),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (LANforge), "toggled",
                      GTK_SIGNAL_FUNC (on_lanforge_button_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (advanced_config_ok), "clicked",
                      GTK_SIGNAL_FUNC (on_advanced_config_ok_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (advanced_config_cancel), "clicked",
                      GTK_SIGNAL_FUNC (on_advanced_config_cancel_clicked),
                      NULL);

  gtk_object_set_data (GTK_OBJECT (advanced_config_dialog), "tooltips", tooltips);

  return advanced_config_dialog;
}

GtkWidget*
create_log_dialog (void)
{
  GtkWidget *log_dialog;
  GtkWidget *dialog_vbox3;
  GtkWidget *log_scrolledwindow;
  GtkWidget *log_text;
  GtkWidget *dialog_action_area3;
  GtkWidget *hbuttonbox3;
  GtkWidget *log_ok;
  GtkWidget *log_clear;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  log_dialog = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (log_dialog), "log_dialog", log_dialog);
  gtk_widget_set_usize (log_dialog, 500, 500);
  gtk_container_set_border_width (GTK_CONTAINER (log_dialog), 2);
  gtk_tooltips_set_tip (tooltips, log_dialog, _("Logs all SIP messages."), NULL);
  gtk_window_set_title (GTK_WINDOW (log_dialog), _("Messages Log"));
  gtk_window_set_position (GTK_WINDOW (log_dialog), GTK_WIN_POS_MOUSE);
  gtk_window_set_policy (GTK_WINDOW (log_dialog), TRUE, TRUE, FALSE);

  dialog_vbox3 = GTK_DIALOG (log_dialog)->vbox;
  gtk_object_set_data (GTK_OBJECT (log_dialog), "dialog_vbox3", dialog_vbox3);
  gtk_widget_show (dialog_vbox3);

  log_scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (log_scrolledwindow);
  gtk_object_set_data_full (GTK_OBJECT (log_dialog), "log_scrolledwindow", log_scrolledwindow,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (log_scrolledwindow);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), log_scrolledwindow, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (log_scrolledwindow), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  log_text = gtk_text_new (NULL, NULL);
  gtk_widget_ref (log_text);
  gtk_object_set_data_full (GTK_OBJECT (log_dialog), "log_text", log_text,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (log_text);
  gtk_container_add (GTK_CONTAINER (log_scrolledwindow), log_text);

  dialog_action_area3 = GTK_DIALOG (log_dialog)->action_area;
  gtk_object_set_data (GTK_OBJECT (log_dialog), "dialog_action_area3", dialog_action_area3);
  gtk_widget_show (dialog_action_area3);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area3), 10);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox3);
  gtk_object_set_data_full (GTK_OBJECT (log_dialog), "hbuttonbox3", hbuttonbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox3);
  gtk_box_pack_start (GTK_BOX (dialog_action_area3), hbuttonbox3, TRUE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox3), GTK_BUTTONBOX_START);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox3), 5);

  log_ok = gtk_button_new_with_label (_("OK"));
  gtk_widget_ref (log_ok);
  gtk_object_set_data_full (GTK_OBJECT (log_dialog), "log_ok", log_ok,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (log_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), log_ok);
  GTK_WIDGET_SET_FLAGS (log_ok, GTK_CAN_DEFAULT);

  log_clear = gtk_button_new_with_label (_("Clear"));
  gtk_widget_ref (log_clear);
  gtk_object_set_data_full (GTK_OBJECT (log_dialog), "log_clear", log_clear,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (log_clear);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), log_clear);
  GTK_WIDGET_SET_FLAGS (log_clear, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (log_dialog), "delete_event",
                      GTK_SIGNAL_FUNC (on_log_dialog_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (log_ok), "clicked",
                      GTK_SIGNAL_FUNC (on_log_ok_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (log_clear), "clicked",
                      GTK_SIGNAL_FUNC (on_log_clear_clicked),
                      NULL);

  gtk_object_set_data (GTK_OBJECT (log_dialog), "tooltips", tooltips);

  return log_dialog;
}

GtkWidget*
create_missing_number_dialog (void)
{
  GtkWidget *missing_number_dialog;
  GtkWidget *dialog_vbox4;
  GtkWidget *missing_number_label;
  GtkWidget *dialog_action_area4;
  GtkWidget *missing_number_ok;

  missing_number_dialog = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (missing_number_dialog), "missing_number_dialog", missing_number_dialog);
  gtk_window_set_title (GTK_WINDOW (missing_number_dialog), _("Error: Missing Number"));
  GTK_WINDOW (missing_number_dialog)->type = GTK_WINDOW_DIALOG;
  gtk_window_set_position (GTK_WINDOW (missing_number_dialog), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (missing_number_dialog), TRUE);
  gtk_window_set_policy (GTK_WINDOW (missing_number_dialog), TRUE, TRUE, FALSE);

  dialog_vbox4 = GTK_DIALOG (missing_number_dialog)->vbox;
  gtk_object_set_data (GTK_OBJECT (missing_number_dialog), "dialog_vbox4", dialog_vbox4);
  gtk_widget_show (dialog_vbox4);

  missing_number_label = gtk_label_new (_("Please enter a number to dial"));
  gtk_widget_ref (missing_number_label);
  gtk_object_set_data_full (GTK_OBJECT (missing_number_dialog), "missing_number_label", missing_number_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (missing_number_label);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), missing_number_label, FALSE, FALSE, 0);
  gtk_label_set_line_wrap (GTK_LABEL (missing_number_label), TRUE);
  gtk_misc_set_padding (GTK_MISC (missing_number_label), 30, 30);

  dialog_action_area4 = GTK_DIALOG (missing_number_dialog)->action_area;
  gtk_object_set_data (GTK_OBJECT (missing_number_dialog), "dialog_action_area4", dialog_action_area4);
  gtk_widget_show (dialog_action_area4);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area4), 10);

  missing_number_ok = gtk_button_new_with_label (_("OK"));
  gtk_widget_ref (missing_number_ok);
  gtk_object_set_data_full (GTK_OBJECT (missing_number_dialog), "missing_number_ok", missing_number_ok,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (missing_number_ok);
  gtk_box_pack_start (GTK_BOX (dialog_action_area4), missing_number_ok, FALSE, FALSE, 0);
  gtk_widget_set_usize (missing_number_ok, 60, -2);

  gtk_signal_connect (GTK_OBJECT (missing_number_ok), "clicked",
                      GTK_SIGNAL_FUNC (on_missing_number_ok_clicked),
                      NULL);

  gtk_widget_grab_focus (missing_number_ok);
  return missing_number_dialog;
}

GtkWidget*
create_incoming_call_dialog (void)
{
  GtkWidget *incoming_call_dialog;
  GtkWidget *dialog_vbox5;
  GtkWidget *incoming_call_label;
  GtkWidget *dialog_action_area5;
  GtkWidget *hbuttonbox4;
  GtkWidget *incoming_call_accept;
  GtkWidget *incoming_call_reject;

  incoming_call_dialog = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (incoming_call_dialog), "incoming_call_dialog", incoming_call_dialog);
  gtk_window_set_title (GTK_WINDOW (incoming_call_dialog), _("Incoming Call"));
  GTK_WINDOW (incoming_call_dialog)->type = GTK_WINDOW_DIALOG;
  gtk_window_set_position (GTK_WINDOW (incoming_call_dialog), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (incoming_call_dialog), TRUE);
  gtk_window_set_policy (GTK_WINDOW (incoming_call_dialog), TRUE, TRUE, FALSE);

  dialog_vbox5 = GTK_DIALOG (incoming_call_dialog)->vbox;
  gtk_object_set_data (GTK_OBJECT (incoming_call_dialog), "dialog_vbox5", dialog_vbox5);
  gtk_widget_show (dialog_vbox5);

  incoming_call_label = gtk_label_new (_("You have an incoming call!"));
  gtk_widget_ref (incoming_call_label);
  gtk_object_set_data_full (GTK_OBJECT (incoming_call_dialog), "incoming_call_label", incoming_call_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (incoming_call_label);
  gtk_box_pack_start (GTK_BOX (dialog_vbox5), incoming_call_label, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (incoming_call_label), 30, 30);

  dialog_action_area5 = GTK_DIALOG (incoming_call_dialog)->action_area;
  gtk_object_set_data (GTK_OBJECT (incoming_call_dialog), "dialog_action_area5", dialog_action_area5);
  gtk_widget_show (dialog_action_area5);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area5), 10);

  hbuttonbox4 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox4);
  gtk_object_set_data_full (GTK_OBJECT (incoming_call_dialog), "hbuttonbox4", hbuttonbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox4);
  gtk_box_pack_start (GTK_BOX (dialog_action_area5), hbuttonbox4, FALSE, FALSE, 0);

  incoming_call_accept = gtk_button_new_with_label (_("Accept"));
  gtk_widget_ref (incoming_call_accept);
  gtk_object_set_data_full (GTK_OBJECT (incoming_call_dialog), "incoming_call_accept", incoming_call_accept,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (incoming_call_accept);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), incoming_call_accept);
  GTK_WIDGET_SET_FLAGS (incoming_call_accept, GTK_CAN_DEFAULT);

  incoming_call_reject = gtk_button_new_with_label (_("Reject"));
  gtk_widget_ref (incoming_call_reject);
  gtk_object_set_data_full (GTK_OBJECT (incoming_call_dialog), "incoming_call_reject", incoming_call_reject,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (incoming_call_reject);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), incoming_call_reject);
  GTK_WIDGET_SET_FLAGS (incoming_call_reject, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (incoming_call_accept), "clicked",
                      GTK_SIGNAL_FUNC (on_incoming_call_accept_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (incoming_call_reject), "clicked",
                      GTK_SIGNAL_FUNC (on_incoming_call_reject_clicked),
                      NULL);

  gtk_widget_grab_focus (incoming_call_accept);
  return incoming_call_dialog;
}

GtkWidget*
create_error_dialog (void)
{
  GtkWidget *error_dialog;
  GtkWidget *dialog_vbox6;
  GtkWidget *error_label;
  GtkWidget *dialog_action_area6;
  GtkWidget *error_ok;

  error_dialog = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (error_dialog), "error_dialog", error_dialog);
  gtk_widget_set_usize (error_dialog, 288, 120);
  gtk_container_set_border_width (GTK_CONTAINER (error_dialog), 18);
  gtk_window_set_title (GTK_WINDOW (error_dialog), _("Error"));
  GTK_WINDOW (error_dialog)->type = GTK_WINDOW_DIALOG;
  gtk_window_set_position (GTK_WINDOW (error_dialog), GTK_WIN_POS_MOUSE);
  gtk_window_set_policy (GTK_WINDOW (error_dialog), TRUE, TRUE, FALSE);

  dialog_vbox6 = GTK_DIALOG (error_dialog)->vbox;
  gtk_object_set_data (GTK_OBJECT (error_dialog), "dialog_vbox6", dialog_vbox6);
  gtk_widget_show (dialog_vbox6);

  error_label = gtk_label_new (_("ERROR!"));
  gtk_widget_ref (error_label);
  gtk_object_set_data_full (GTK_OBJECT (error_dialog), "error_label", error_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (error_label);
  gtk_box_pack_start (GTK_BOX (dialog_vbox6), error_label, FALSE, FALSE, 0);

  dialog_action_area6 = GTK_DIALOG (error_dialog)->action_area;
  gtk_object_set_data (GTK_OBJECT (error_dialog), "dialog_action_area6", dialog_action_area6);
  gtk_widget_show (dialog_action_area6);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area6), 10);

  error_ok = gtk_button_new_with_label (_("OK"));
  gtk_widget_ref (error_ok);
  gtk_object_set_data_full (GTK_OBJECT (error_dialog), "error_ok", error_ok,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (error_ok);
  gtk_box_pack_start (GTK_BOX (dialog_action_area6), error_ok, FALSE, FALSE, 0);
  gtk_widget_set_usize (error_ok, 50, -2);

  gtk_signal_connect (GTK_OBJECT (error_ok), "clicked",
                      GTK_SIGNAL_FUNC (on_error_ok_clicked),
                      NULL);

  gtk_widget_grab_focus (error_ok);
  return error_dialog;
}

GtkWidget*
create_fatal_error_dialog (void)
{
  GtkWidget *fatal_error_dialog;
  GtkWidget *dialog_vbox7;
  GtkWidget *fatal_error_label;
  GtkWidget *dialog_action_area7;
  GtkWidget *fatal_error_ok;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  fatal_error_dialog = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (fatal_error_dialog), "fatal_error_dialog", fatal_error_dialog);
  gtk_widget_set_usize (fatal_error_dialog, 288, 120);
  gtk_container_set_border_width (GTK_CONTAINER (fatal_error_dialog), 18);
  gtk_window_set_title (GTK_WINDOW (fatal_error_dialog), _("Error"));
  GTK_WINDOW (fatal_error_dialog)->type = GTK_WINDOW_DIALOG;
  gtk_window_set_position (GTK_WINDOW (fatal_error_dialog), GTK_WIN_POS_MOUSE);
  gtk_window_set_policy (GTK_WINDOW (fatal_error_dialog), TRUE, TRUE, FALSE);

  dialog_vbox7 = GTK_DIALOG (fatal_error_dialog)->vbox;
  gtk_object_set_data (GTK_OBJECT (fatal_error_dialog), "dialog_vbox7", dialog_vbox7);
  gtk_widget_show (dialog_vbox7);

  fatal_error_label = gtk_label_new (_("FATAL ERROR!"));
  gtk_widget_ref (fatal_error_label);
  gtk_object_set_data_full (GTK_OBJECT (fatal_error_dialog), "fatal_error_label", fatal_error_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (fatal_error_label);
  gtk_box_pack_start (GTK_BOX (dialog_vbox7), fatal_error_label, FALSE, FALSE, 0);

  dialog_action_area7 = GTK_DIALOG (fatal_error_dialog)->action_area;
  gtk_object_set_data (GTK_OBJECT (fatal_error_dialog), "dialog_action_area7", dialog_action_area7);
  gtk_widget_show (dialog_action_area7);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area7), 10);

  fatal_error_ok = gtk_button_new_with_label (_("OK"));
  gtk_widget_ref (fatal_error_ok);
  gtk_object_set_data_full (GTK_OBJECT (fatal_error_dialog), "fatal_error_ok", fatal_error_ok,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (fatal_error_ok);
  gtk_box_pack_start (GTK_BOX (dialog_action_area7), fatal_error_ok, FALSE, FALSE, 0);
  gtk_widget_set_usize (fatal_error_ok, 50, -2);
  gtk_tooltips_set_tip (tooltips, fatal_error_ok, _("Stop program"), NULL);

  gtk_signal_connect (GTK_OBJECT (fatal_error_ok), "clicked",
                      GTK_SIGNAL_FUNC (on_fatal_error_ok_clicked),
                      NULL);

  gtk_widget_grab_focus (fatal_error_ok);
  gtk_object_set_data (GTK_OBJECT (fatal_error_dialog), "tooltips", tooltips);

  return fatal_error_dialog;
}

