/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main_window (void);
GtkWidget* create_basic_config_dialog (void);
GtkWidget* create_advanced_config_dialog (void);
GtkWidget* create_log_dialog (void);
GtkWidget* create_missing_number_dialog (void);
GtkWidget* create_incoming_call_dialog (void);
GtkWidget* create_error_dialog (void);
GtkWidget* create_fatal_error_dialog (void);
