/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include <signal.h>

#include "callbacks.h"
#include "configuration.h"
#include "interface.h"
#include "support.h"

#include "VideoEnable.h"

/****************** globals *****************/
GtkWidget *main_window;
GtkWidget *log_dialog;
GtkWidget *basic_config_dialog;
GtkWidget *advanced_config_dialog;
int videoEnabled = 0;
int lanforgeEnabled = 0;
extern GtkWidget*  main_window_manager;
int
main (int argc, char *argv[])
{
  /* catch termination signals */
  signal(SIGHUP, &fatal_error_signal);
  signal(SIGINT, &fatal_error_signal);
  signal(SIGQUIT, &fatal_error_signal);
  signal(SIGTERM, &fatal_error_signal);
  signal(SIGKILL, &fatal_error_signal);

#ifdef ENABLE_NLS
  bindtextdomain (PACKAGE, PACKAGE_LOCALE_DIR);
  textdomain (PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  main_window = create_main_window ();

  log_dialog = create_log_dialog();
  sipset_init();

  gtk_widget_set_usize (main_window, 380, 170);
  gtk_window_set_policy( GTK_WINDOW( main_window ), TRUE, TRUE, TRUE );
#ifdef USE_MPEGLIB
  if(videoEnabled)
  {
      VideoDevice_preview_init(main_window, main_window_manager);
      gtk_widget_set_usize (main_window, 380, 350);
  }
#endif

  gtk_widget_show (main_window);

  gtk_main ();
  return 0;
}

