# $Id: Makefile,v 1.1 2004/05/01 04:15:23 greear Exp $

BUILD = ../../build

include $(BUILD)/Makefile.pre

TARGET_LIBRARY=librtspif

PACKAGES += RTSP SDP PTHREAD UTIL

TESTPROGRAMS = \

# name of all files to be compiled (don't include header files)
SRC = \
    RtspMsgInterface.cxx

include $(BUILD)/Makefile.post
