# $Id: Makefile,v 1.1 2004/05/01 04:15:23 greear Exp $

# $Log: Makefile,v $
# Revision 1.1  2004/05/01 04:15:23  greear
# Initial revision
#
# Revision 1.4  2001/04/17 22:04:06  kimle
# added new test program: printRtpFormat
#
# Revision 1.3  2001/04/13 03:01:37  wjin
# add sys statistics
#
# Revision 1.2  2001/02/24 03:22:03  wjin
# *** empty log message ***
#
# Revision 1.1  2001/02/22 04:22:02  wjin
# add files
#

BUILD = ../../../build

include $(BUILD)/Makefile.pre


PACKAGES += RTSP SDP PTHREAD UTIL


TESTPROGRAMS = \
    printRtpFormat.cxx \
#    testDuration.cxx \
#    testTimer.cxx \
#    testTimer2.cxx \
#    testTimer3.cxx \

# name of all files to be compiled (don't include header files)
SRC = \


include $(BUILD)/Makefile.post
