# $Id: Makefile,v 1.1 2004/05/01 04:15:16 greear Exp $

BUILD = ../../build

include $(BUILD)/Makefile.pre

PACKAGES += MEDIALIB PTHREAD LIBSNDCARD RTP SDP2 UTIL LIBCEXT LIBXML

CODE_SUBDIRS =  

VERIFY_TESTCASES = \
	SdpCreate.cxx  \
        NegotiateSdp.cxx \
        MediaTest.cxx \
        MediaTest2.cxx


SRC = \

include $(BUILD)/Makefile.post
