# $Id: Makefile,v 1.1 2004/05/01 04:15:33 greear Exp $
#

BUILD = ../../../build

include $(BUILD)/Makefile.pre

# DEFINES += 
#

PACKAGES += UTIL PTHREAD


# names of programs (e.g. test programs) to be compiled
#

TESTPROGRAMS = \
        vmd5sum.c
	
	
include $(BUILD)/Makefile.post
