# $Id: Makefile,v 1.1 2004/05/01 04:15:24 greear Exp $
#

BUILD = ../../../build

include $(BUILD)/Makefile.pre

PACKAGES += SDP2 UTIL PTHREAD LIBXML OPENSSL LIBCEXT OPENSSL

# names of programs (e.g. test programs) to be compiled
#

# names of programs (e.g. test programs) to be compiled
#TESTPROGRAMS = \
#	Sdp2Test.cxx 

VERIFY_TESTCASES = \
	Sdp2AttributeTest.cxx\
	Sdp2SessionTest.cxx\
	Sdp2ConnectionTest.cxx

include $(BUILD)/Makefile.post
