# $Id: Makefile,v 1.1 2004/05/01 04:15:33 greear Exp $
#

BUILD = ../../../build

include $(BUILD)/Makefile.pre

# DEFINES += 
#

PACKAGES += TRANSPORT UTIL PTHREAD


# names of programs (e.g. test programs) to be compiled
#

TESTPROGRAMS = \
        cpLogTestPriorities.cxx \
        cpLogTestTrafficGenerator.cxx \
    	VLogTest.cxx \
	
	
	
include $(BUILD)/Makefile.post
