# $Id: Makefile,v 1.1 2004/05/01 04:15:23 greear Exp $

BUILD = ../../build

include $(BUILD)/Makefile.pre

TARGET_LIBRARY=librtsp

PACKAGES += RTSP SDP RTP PTHREAD UTIL

TESTPROGRAMS = \
    RtspClientInteract.cxx \
#    RtspTcpClient.cxx \
#    RtspClient.cxx \

# name of all files to be compiled (don't include header files)
SRC = \

include $(BUILD)/Makefile.post
