# $Id: Makefile,v 1.1 2004/05/01 04:14:55 greear Exp $

BUILD = ../build

include $(BUILD)/Makefile.pre

PACKAGES += UTIL PTHREAD

# names of programs (e.g. test programs) to be compiled
TESTPROGRAMS = radtest.cxx

# name of all files to be compiled (don't include header files)
SRC = \
	RadiusStack.cxx \
	TestClient.cxx

include $(BUILD)/Makefile.post
