#! /bin/sh

echo "**************************************************************"
echo "* This file has been deprecated. Please use vocalctl instead *"
echo "**************************************************************"
