# $Id: Makefile,v 1.1 2004/05/01 04:15:38 greear Exp $
#

BUILD = ../../../build

include $(BUILD)/Makefile.pre

# DEFINES += 
#

PACKAGES += TRANSPORT UTIL PTHREAD


# names of programs (e.g. test programs) to be compiled
#

TESTPROGRAMS = \
	tTemplates.cxx		\
    	tAddressFamily.cxx	\
    	tIPAddress.cxx	    	\
    	tIP6Address.cxx	    	\
	tSocket.cxx		\
	tServer.cxx		\
	tClient.cxx		\
	tEvent.cxx		\
	tService.cxx		\
	tPthreadSignals.cxx	\
	tSignals.cxx		\
	tFifoTimer.cxx		\
	tProtocol.cxx		\
	tFifoCancel.cxx 	\
	tTimeVal.cxx		\
	tFifoTest.cxx		\
	tPipe.cxx		\
        tRWMutex.cxx            \
        tUDPSocket.cxx          \
        tUDPClientServer.cxx    \
        udpInjectRcv.cxx        \
        udpInjectSnd.cxx        \
        SingletonTest.cxx


include $(BUILD)/Makefile.post
