# $Id: Makefile,v 1.1 2004/05/01 04:15:36 greear Exp $

BUILD = ../../../build

include $(BUILD)/Makefile.pre

PACKAGES += TRANSPORT UTIL LIBXML PTHREAD


# names of programs (e.g. test programs) to be compiled
#

TESTPROGRAMS = \
	TickCount.cxx	\
	Statistic.cxx	\
	Perf.cxx
	
	
include $(BUILD)/Makefile.post
