# $Id: Makefile,v 1.1 2004/05/01 04:15:38 greear Exp $

# $Log: Makefile,v $
# Revision 1.1  2004/05/01 04:15:38  greear
# Initial revision
#
# Revision 1.1  2000/06/20 02:57:35  chok
# Add test program to generate boring messages
#

BUILD = ../../../build

include $(BUILD)/Makefile.pre

DEFINES += USE_PTHREADS

PACKAGES += PTHREAD UTIL

TESTPROGRAMS = \
	udpMsgTest.cxx \

SRC = \

include $(BUILD)/Makefile.post
